
 version: '3.8'
 
 services:
    laravel-app:
      build: .
      volumes:
      - ./:/var/www/html
      ports:
      - 8080:80
      environment:
      - "DB_CONNECTION= mysql"
      - "DB_HOST= db"
      - "DB_PORT= 3306"
      - "DB_DATABASE= test"
      - "DB_USERNAME= root"
      - "DB_PASSOWRD= password"  
      depends_on:
      - db
        
    db:
     image: mysql:5.7
     ports:
       - 3306
     environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: password
     
    phpmyadmin:
     image: phpmyadmin/phpmyadmin
     ports:
      - 81:80
     depends_on:
      - db

