
 version: '3.8'
 
  services:
    laravel-app:
      build: .
    volumes:
      - ./website:/var/www/html
    ports:
      - 8080:80
      depends_on:
     - db
 services:
        db:
           image: mysql:5.7
        ports:
      - “3306:3306”
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: password
  services:
     phpmyadmin:
        image: phpmyadmin/phpmyadmin
      ports:
      - “81:80”
   depends_on:
      - db

